apiVersion: v1
kind: Service
metadata:
  name: product-management-service
spec:
  selector:
    app: product-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
